---
version: 1

kind: experiment

framework: pytorch

tags: [healthy_val_with_filter_122220_4800_no_norm]
 
build:
  image: pytorch/pytorch:1.2-cuda10.0-cudnn7-runtime
  build_steps:
    - pip install -r requirements.txt

environment:
  resources:
    cpu:
      requests: 0
      limits: 0
    memory:
      requests: 20000
      limits: 30000
    gpu:
      requests: 1
      limits: 1

declarations:
  size: 64
  data_dir: '/data/PMSD_voxelmorph/healthy64/'
  atlas_dir: '/data/PMSD_voxelmorph/healthy_atlas/'
  model: 'vm2'
  init_model_file: '/outputs/agrund/PMSD_voxelmorph/experiments/121338/1000.ckpt'
  nr_val_data: 1

run:
  cmd: python -u test.py --size={{ size }}\
                             --data_dir={{ data_dir }}\
                             --atlas_dir={{ atlas_dir }}\
                             --init_model_file={{ init_model_file }}\
                             --nr_val_data={{ nr_val_data }}